###########
#PBS -N DoradoBaseCalling
#PBS -l ncpus=8,mem=60GB,walltime=148:00:00,ngpus=1
#PBS -q gpu
#PBS -m ae
#PBS -M user@email.com
###########


module load gpu/dorado/0.7.1


filepath="/path/to/pod5/"

#ensure you use the approriate tranformer model based on Nanopore machine and flow cell version
#IMPORTANT : specify --no trim to retain post-polyA barcode

dorado basecaller --no-trim dna_r10.4.1_e8.2_400bps_sup@v5.0.0 --emit-fastq  $filepath > file_sup@v5.0.0.fastq
gzip file_sup@v5.0.0.fastq



