
###########
#PBS -N Pileup
#PBS -l ncpus=2,mem=35GB,walltime=01:40:00
#PBS -m ae
#PBS -M user@email.com
###########


module load bcftools/1.19

#SNP positions in bed format
positions='SNPs.bed'
#genome in fasta format
genome='genome.fa'
#Mapped read in bam format
bams="*bam"

bcftools mpileup --regions-file $positions -d 10000 --annotate FORMAT/AD,FORMAT/ADF,FORMAT/ADR,FORMAT/DP,FORMAT/SP,INFO/AD,INFO/ADF,INFO/ADR $bams --fasta-ref $genome |  bcftools query --format '%CHROM\t%POS\t%REF\t%ALT[\t%AD]\n' > SNPs

